apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 45.27.2
    helm:
      values: |
        grafana:
          adminPassword: EasyShopAdmin123
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: selfsigned-issuer
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/ssl-verify: "false"
              nginx.ingress.kubernetes.io/hsts: "false"
            hosts:
              - grafana.shaheen.homes
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.shaheen.homes
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'argocd'
                orgId: 1
                folder: 'ArgoCD'
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/argocd
          dashboards:
            argocd:
              argocd-dashboard:
                gnetId: 14584
                revision: 1
                datasource: Prometheus
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: selfsigned-issuer
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/ssl-verify: "false"
              nginx.ingress.kubernetes.io/hsts: "false"
            hosts:
              - prometheus.shaheen.homes
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus.shaheen.homes
        # Add ArgoCD ServiceMonitor
        additionalServiceMonitors:
          - name: argocd
            selector:
              matchLabels:
                app.kubernetes.io/part-of: argocd
            namespaceSelector:
              matchNames:
                - argocd
            endpoints:
              - port: metrics
                interval: 30s
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true