apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-0.mongodb-service.easyshop.svc.cluster.local:27017/easyshop"
  REDIS_URI: "redis://easyshop-redis.easyshop.svc.cluster.local:6379"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://app.shaheen.homes/api" 
  NEXTAUTH_URL: "https://app.shaheen.homes"  
  NEXTAUTH_SECRET: "HmaFjYZ2jbUK7Ef+wZrBiJei4ZNGBAJ5IdiOGAyQegw="
  JWT_SECRET: "e5e425764a34a2117ec2028bd53d6f1388e7b90aeae9fa7735f2469ea3a6cc8c"
